"""Samsung HW-Q990B IR codes learned from the AH81-09773A remote.

Protocol: Samsung IR (similar to NEC, 38 kHz carrier).
Codes are stored as base64-encoded Broadlink IR packets, converted to
raw microsecond timings at runtime for the infrared platform.
"""

from __future__ import annotations

import base64
from enum import Enum
from typing import override

from infrared_protocols import Command

CARRIER_FREQ_HZ = 38_000

# Broadlink timing conversion constant (~30.42 µs per tick)
_TICK_US = 8192.0 / 269.0


def _broadlink_b64_to_timings(b64: str) -> list[int]:
    """Convert a base64 Broadlink IR packet to signed µs timings."""
    packet = base64.b64decode(b64)
    if len(packet) < 4 or packet[0] != 0x26:
        raise ValueError(f"Invalid Broadlink IR packet (type=0x{packet[0]:02X})")

    length = packet[2] | (packet[3] << 8)
    data = packet[4:4 + length]

    timings: list[int] = []
    i = 0
    is_pulse = True
    while i < len(data):
        if data[i] == 0x00 and i + 2 < len(data):
            ticks = (data[i + 1] << 8) | data[i + 2]
            i += 3
        else:
            ticks = data[i]
            i += 1

        if ticks == 0:
            break

        us = round(ticks * _TICK_US)
        timings.append(us if is_pulse else -us)
        is_pulse = not is_pulse

    return timings


class Q990BCode(Enum):
    """IR command codes for the Samsung HW-Q990B soundbar.

    Values are base64-encoded Broadlink IR packets learned from the AH81-09773A remote.
    """

    POWER = "JgCgAJGUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8RDxEPEQ8RDxEPMg8yDzIPEQ8yDzIPMg8yDxEPEQ8RDzIPAAcbkpQPEQ8RDxEPEQ8yDzIOEQ8RDzIPMg8yDzIPEQ8RDxEPEQ+VDxEPEQ8RDxEPEQ8SDhEPEg4yDzIOMg8RDzIPMg4yDzIOEQ8SDhEPMg8ADQQ="
    VOLUME_UP = "JgCgAJGUDhEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxIOlQ8RDxEPEQ8RDzIPMg8yDxEPMg8yDzIPEg4RDxEPEg4yDhEPEg4RDzIPAAcckpQOEQ8RDxEPEQ8yDzIPEQ8RDzIPMg8yDzIPEQ8RDxEPEQ+VDxEPEg4RDxIOMg8zDjIPEQ8yDzIPMg8RDxIOEg4SDjIPEg4SDhIOMg8ADQQ="
    VOLUME_DOWN = "JgCgAJGUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEg4RDxEPlQ8RDxEPEQ8RDxEPEQ8RDzIPMg8yDzIPEQ8yDzIPMw4RDxEPEQ8RDzIPAAcckpQPEQ8RDxEPEQ8yDjIPEQ8RDzIPMg8yDzIPEQ8RDxEPEQ+VDxIOEg4SDhEPEQ8RDxEPMg8yDzIPMg8SDjIOMg8yDxIOEg4SDhIOMg4ADQQ="
    MUTE = "JgCgAJGUDxEPEQ8RDxIOMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ4RDxEPEQ8RDzIPEQ8RDxEPMg8yDzIPEQ8RDzIPMg8yDxEPEg4RDzIPAAcckpQPEQ8RDxEPEQ8yDzIOEQ8RDzIOMg4yDzIPEg4RDxEPEQ+VDxEPEQ8RDxIOMg8RDxIOEg4yDzIPMg8RDxIOMg8yDzIPEQ8SDhIOMg4ADQQ="
    SOURCE = "JgCgAJKUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ4RDxEPEQ8RDzIPEQ8yDxEPMg8yDzIPEQ8RDzIPEQ8yDxEPEQ8RDzIPAAcckpQPEQ8RDxEPEQ8yDzIPEQ8RDzIPMg8yDzIPEQ8SDhEPEQ+VDxEPEQ8RDxEPMg8SDjIPEg4yDzIPMg8SDhEPMg8RDzIPEQ8SDhEPMg8ADQQ="
    SOUND_MODE = "JgCgAJKUDhEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8RDzIPMw4RDzIPMg8yDzIPEQ8RDxEPMg8RDxEPEQ8RDzIPAAcbkpQPEQ8RDxEPEQ8yDzIPEQ8RDzIPMg8yDzIOEQ8RDxEPEQ+VDxEPEQ8RDxEPMg8yDxEPMg8yDzIPMg8RDxEPEQ8yDxEPEQ8RDxIOMg8ADQQ="
    BASS_UP = "JgBQAJCUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8RDxEPMg8RDxEPEQ8REBAPMg8yDxEPMg8yDzIPMg8yDxEPAA0E"
    BASS_DOWN = "JgCgAJKUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8RDzIPMg8RDxEPEQ8RDxEPMg8RDxEPMg8yDzIPMg8yDxEPAAcckpQOEQ8RDxEPEQ8yDzIPEQ8RDzIPMg8yDzIPEQ8RDxEPEQ+VDxEPEQ8RDxEPMg8yDxEPEQ8RDxEPEQ8yDxEPEQ8yDzIPMg8yDzIPEg4ADQQ="
    BLUETOOTH_PAIR = "JgCgAJGUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8SDhEPlQ8RDxEPEg4RDzIPMg8yDxEPMg8yDxIOMg8RDxEPEQ8yDxEPEg4yDxEPAAcckpQPEQ8RDxEPEQ8yDjIPEQ4RDzIPMg8yDzIPEQ8RDxIOEQ+VDxIOEQ8RDxEPMg8yDjIPEQ8yDzIPEQ8yDxEPEQ8SDjIPEg4SDjIPEg4ADQQ="
    INFO = "JgCgAJGUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8RDxEPMg8RDxEPEQ8RDzIPMg8yDxEOMg8yDzIPMg8RDxEPAAcckpQPEQ8RDxEPEg4yDjIPGQcRDzIPMg8yDzIPEQ4RDxEPEQ+VDhEPEQ8RDxEPEQ8yDxIOEQ8RDxIOMg8yDzIPEQ8yDzIPMg8yDxEPEQ8ADQQ="
    CH_LEVEL = "JgCgAJGUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8RDxEPEQ8RDzIOEQ8RDxEPMg8yDzIPMg8RDzIOMg8yDxIOAAcckpQPEQ8RDxEPEQ8yDzIPEQ8RDzIPMg8yDzIPEQ8RDxEPEQ+VDxEPEg4RDxEPEQ8RDxEPMg8RDhEPEQ8yDzIPMg8yDxIOMg8yDzIPEQ8ADQQ="
    SETTINGS = "JgBQAJKUDhEPEg4RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8SDhEPMg8yDxEPEQ8yDxEPMg8yDxEPEQ8yDzIPEQ8yDxEPAA0E"
    TONE_CONTROL = "JgCgAJKUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ4RDxEPEQ8RDxEPEQ8RDzIPMg8RDxEPMg8yDzIPMg4RDxEPMg8yDxEPAAcckpQPEQ8RDxEPEQ8yDzIPEQ8RDzIOMg8yDzIPEQ8RDxEPEQ+VDxEPEQ8RDxEPEQ8RDxIOMg8yDxEPEQ8yDzIPMg8yDxEPEg4yDzIPEg4ADQQ="
    PLAY_PAUSE = "JgCgAJKUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIOMg8yDxIOEQ8RDxEPlQ8RDxEPEQ8RDxEPMg8RDzIPEQ8RDxEPMg8yDxEOMg8RDzIPMg8yDhEPAAcbkpQPEQ8RDxEPEQ8yDzIPEQ8RDzIPMg8yDzIPEQ8RDxEPEg6VDxEPEg4RDxEPEQ8yDxEPMg8RDxEPEQ8yDzIPEQ8yDxEPMg8yDzIPEg4ADQQ="
    UP = "JgBQAJKUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8RDxEPEQ8yDxEPMg8yDxEPMg8yDzIPEQ8yDxEPEQ8yDxEPAA0E"
    DOWN = "JgBQAJCUDxEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8RDzIPEQ8yDxEPMg8yDxEPMg8RDzIPEQ8yDxEPEQ8yDxEPAA0E"
    LEFT = "JgCgAJGUDxEPEQ8TDREPMg8yDhEPEQ8yDjIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8RDxEPEQ8RDxEPMg8yDxEPMg8yDzIPMg8yDxEPEQ8yDhEPAAcbkpQOEQ8RDxEPEg4yDzIPEQ8RDzIPMg8yDzIPEQ8RDxEPEQ+VDhEPEQ8RDxEPEQ8SDhIOEQ8yDzIPEQ8yDzIPMg8yDzIPEQ8RDzIPEg4ADQQ="
    RIGHT = "JgBQAJGUDhEPEQ8RDxEPMg8yDxEPEQ8yDzIPMg8yDxEPEQ8RDxEPlQ8RDxEPEQ8RDzIPEQ8RDxEPMg8yDxEPMg8SDjIPMg8zDhEPEQ8yDxEPAA0E"


class Q990BCommand(Command):
    """IR command for the Samsung HW-Q990B soundbar."""

    def __init__(self, code: Q990BCode) -> None:
        super().__init__(modulation=CARRIER_FREQ_HZ, repeat_count=0)
        self._code = code
        self._timings: list[int] | None = None

    @override
    def get_raw_timings(self) -> list[int]:
        if self._timings is None:
            self._timings = _broadlink_b64_to_timings(self._code.value)
        return self._timings
